-- くまっちパズル: ランキング用テーブル
-- Supabaseダッシュボードの「SQL Editor」にこの内容を貼り付けて実行してください。

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 12),
  score integer not null check (score >= 0),
  level integer not null default 1 check (level >= 1),
  mode text not null default 'solo' check (mode in ('solo', 'battle')),
  created_at timestamptz not null default now()
);

-- 検索を速くするためのインデックス(スコア降順で上位を取るため)
create index if not exists scores_mode_score_idx on public.scores (mode, score desc);

-- Row Level Security を有効化
alter table public.scores enable row level security;

-- 誰でもランキングを閲覧できる
drop policy if exists "Anyone can read scores" on public.scores;
create policy "Anyone can read scores"
  on public.scores
  for select
  using (true);

-- 誰でもスコアを登録できる(匿名投稿を許可)
drop policy if exists "Anyone can insert scores" on public.scores;
create policy "Anyone can insert scores"
  on public.scores
  for insert
  with check (true);

-- 重要: RLSポリシーだけでなく、テーブルへの基本権限(GRANT)も必要
-- SQL Editorから直接テーブルを作った場合、anon/authenticatedロールに
-- 権限が自動付与されないことがあり、これが「登録できない」原因になりやすい
grant usage on schema public to anon, authenticated;
grant select, insert on public.scores to anon, authenticated;

-- 追加カラム: AI対戦の「勝利までの秒数」ランキング用、ソロプレイの「プレイ時間」表示用
alter table public.scores add column if not exists duration_seconds integer;
alter table public.scores add column if not exists difficulty text check (difficulty in ('easy','normal','hard','master'));

-- AI対戦ランキング(難易度別・タイム昇順)を速くするための部分インデックス
create index if not exists scores_battle_diff_duration_idx
  on public.scores (mode, difficulty, duration_seconds asc)
  where mode = 'battle';

-- 同じ名前の重複を防ぐため、自己ベストの更新(UPDATE)を許可する
-- (削除は行わず、既存の行を上書きする方式。一覧側は名前ごとの最良の1件だけを表示する)
drop policy if exists "Anyone can update scores" on public.scores;
create policy "Anyone can update scores"
  on public.scores
  for update
  using (true)
  with check (true);

grant update on public.scores to anon, authenticated;

-- 安全装置: 記録が「悪化」する更新(ソロ=スコアが下がる、AI対戦=タイムが遅くなる)を
-- データベース側でも拒否する(クライアントのバグや不正な直接アクセスからも保護する)
create or replace function public.prevent_score_regression()
returns trigger
language plpgsql
as $$
begin
  if new.mode = 'solo' and new.score < old.score then
    raise exception 'new score (%) must be higher than existing best (%)', new.score, old.score;
  end if;
  if new.mode = 'battle' and old.duration_seconds is not null
     and new.duration_seconds is not null
     and new.duration_seconds > old.duration_seconds then
    raise exception 'new time (%) must be faster than existing best (%)', new.duration_seconds, old.duration_seconds;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_score_regression on public.scores;
create trigger trg_prevent_score_regression
  before update on public.scores
  for each row execute function public.prevent_score_regression();

-- 削除はクライアントから一切許可しない(ポリシーを作らないことで自動的に拒否されます)
