-- くまっちパズル: ランキング用テーブル
-- Supabaseダッシュボードの「SQL Editor」にこの内容を貼り付けて実行してください。

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 12),
  score integer not null check (score >= 0),
  level integer not null default 1 check (level >= 1),
  mode text not null default 'solo' check (mode in ('solo', 'battle')),
  created_at timestamptz not null default now()
);

-- 検索を速くするためのインデックス(スコア降順で上位を取るため)
create index if not exists scores_mode_score_idx on public.scores (mode, score desc);

-- Row Level Security を有効化
alter table public.scores enable row level security;

-- 誰でもランキングを閲覧できる
drop policy if exists "Anyone can read scores" on public.scores;
create policy "Anyone can read scores"
  on public.scores
  for select
  using (true);

-- 誰でもスコアを登録できる(匿名投稿を許可)
drop policy if exists "Anyone can insert scores" on public.scores;
create policy "Anyone can insert scores"
  on public.scores
  for insert
  with check (true);

-- 重要: RLSポリシーだけでなく、テーブルへの基本権限(GRANT)も必要
-- SQL Editorから直接テーブルを作った場合、anon/authenticatedロールに
-- 権限が自動付与されないことがあり、これが「登録できない」原因になりやすい
grant usage on schema public to anon, authenticated;
grant select, insert on public.scores to anon, authenticated;

-- 追加カラム: AI対戦の「勝利までの秒数」ランキング用、ソロプレイの「プレイ時間」表示用
alter table public.scores add column if not exists duration_seconds integer;
alter table public.scores add column if not exists difficulty text check (difficulty in ('easy','normal','hard','master'));

-- AI対戦ランキング(難易度別・タイム昇順)を速くするための部分インデックス
create index if not exists scores_battle_diff_duration_idx
  on public.scores (mode, difficulty, duration_seconds asc)
  where mode = 'battle';

-- 更新・削除はクライアントから一切許可しない(ポリシーを作らないことで自動的に拒否されます)
